version: '3.4'

services:
  offer.data:
    image: redis:alpine
    
  offer.api:
    image: ${REGISTRY:-demo}/offer.api:${TAG:-latest}
    build:
      context: .
      dockerfile: src/Services/Offer/Offer.Api/Dockerfile 
      
    depends_on:
      - offer.data
 